# Generated by Django 4.2 on 2023-05-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_flashnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='slider/')),
                ('news_type', models.CharField(max_length=100)),
                ('news_desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
