# Generated by Django 4.2 on 2023-05-22 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_website_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website_setting',
            name='favicon',
        ),
    ]
