# Generated by Django 4.2 on 2023-05-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_teg_article_tegs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(max_length=60)),
                ('video_url', models.CharField(max_length=100)),
                ('video_thumb', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
            ],
        ),
    ]
