# Generated by Django 4.2 on 2023-05-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='latestvideo/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
