# Generated by Django 4.2 on 2023-05-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_latestvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='sportlights/')),
                ('author_name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_display', models.BooleanField(default=False)),
                ('is_celebrity_news', models.BooleanField(default=False)),
                ('tegs', models.ManyToManyField(to='website.teg')),
            ],
        ),
    ]
