# Generated by Django 4.2 on 2023-05-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_sportlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportlight',
            name='is_actives',
            field=models.BooleanField(default=True),
        ),
    ]
