# Generated by Django 4.2 on 2023-05-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_sportlight_is_actives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportlight',
            name='is_actives',
            field=models.BooleanField(default=False),
        ),
    ]
