# Generated by Django 4.2 on 2023-07-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='html_file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
